---
name: Build
"on":
  pull_request:
    branches:
      - master
      - 31
      - 32
  push:
    branches:
      - master
      - 31
      - 32
    paths-ignore:
      - "README.md"
  schedule:
    - cron: "5 8 * * 1"

jobs:
  # Ensure the image builds and ansible is installed.
  test:
    name: Test
    runs-on: ubuntu-latest

  steps:
    - name: Checkout.
      uses: actions/checkout@v2

    - name: Build the image.
      run: docker build -t docker-ansible .

    - name: Create a container from the built image.
      run: docker run --name instance -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

    - name: Verify systemd is working.
      run: docker exec --tty instance systemctl list-unit-files --no-pager

    - name: Verify Ansible is working.
      run: docker exec --tty instance ansible --version

  # Build and release the image - latest tag.
  release-latest:
    name: Release latest tag
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image [master branch]
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository }}:latest

  # Build and release the image - 32 tag.
  release-32:
    name: Release 32 tag
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/32'

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image [master branch]
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository }}:32

  # Build and release the image - 31 tag.
  release-31:
    name: Release 31 tag
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/31'

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image [master branch]
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ github.repository }}:31
